/* Generated by cbindgen from terminal-ffi. Do not edit by hand (PRD §14). */

#ifndef TERMINAL_H
#define TERMINAL_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Modifier bits. `Cmd` is deliberately absent: on macOS it means an
 * application command, and those never reach the engine (PRD §8).
 */
#define TERMINAL_MOD_SHIFT (1 << 0)

#define TERMINAL_MOD_ALT (1 << 1)

#define TERMINAL_MOD_CTRL (1 << 2)

/**
 * The result of a fallible call. Out-parameters carry results; the return
 * value carries status (PRD §12).
 */
enum TerminalStatus
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    TerminalStatus_Ok = 0,
    /**
     * The handle, or a required out-parameter, was null.
     */
    TerminalStatus_NullHandle = -1,
    /**
     * A panic was caught at the boundary. The session may be damaged, but the
     * process is still alive.
     */
    TerminalStatus_Panicked = -2,
    /**
     * An argument was malformed — a null buffer with a non-zero length, text
     * that is not UTF-8, a size of zero.
     */
    TerminalStatus_InvalidArgument = -3,
    /**
     * The shell could not be started.
     */
    TerminalStatus_SpawnFailed = -4,
    /**
     * Writing to the pty failed; the shell has probably gone.
     */
    TerminalStatus_IoError = -5,
    /**
     * The caller's buffer was too small. The out-parameter says how much is
     * needed; nothing was copied.
     */
    TerminalStatus_BufferTooSmall = -6,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum TerminalStatus TerminalStatus;
#else
typedef int32_t TerminalStatus;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * Which key was pressed. `Char` carries its character in
 * [`TerminalKeyEvent::codepoint`]; `F` and `KeypadDigit` carry their number in
 * [`TerminalKeyEvent::number`].
 */
enum TerminalKeyCode
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    TerminalKeyCode_Char = 0,
    TerminalKeyCode_Enter,
    TerminalKeyCode_Tab,
    TerminalKeyCode_Backspace,
    TerminalKeyCode_Escape,
    TerminalKeyCode_Delete,
    TerminalKeyCode_Insert,
    TerminalKeyCode_Up,
    TerminalKeyCode_Down,
    TerminalKeyCode_Right,
    TerminalKeyCode_Left,
    TerminalKeyCode_Home,
    TerminalKeyCode_End,
    TerminalKeyCode_PageUp,
    TerminalKeyCode_PageDown,
    TerminalKeyCode_F,
    TerminalKeyCode_KeypadDigit,
    TerminalKeyCode_KeypadEnter,
    TerminalKeyCode_KeypadPlus,
    TerminalKeyCode_KeypadMinus,
    TerminalKeyCode_KeypadMultiply,
    TerminalKeyCode_KeypadDivide,
    TerminalKeyCode_KeypadDecimal,
    TerminalKeyCode_KeypadEquals,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum TerminalKeyCode TerminalKeyCode;
#else
typedef int32_t TerminalKeyCode;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * The terminal, as C sees it: a token it stores and hands back, and never
 * dereferences.
 */
typedef struct TerminalSession TerminalSession;

/**
 * A screen size in cells.
 */
typedef struct TerminalSize {
    uint16_t rows;
    uint16_t cols;
} TerminalSize;

/**
 * A borrowed UTF-8 byte buffer: pointer plus explicit length, never
 * NUL-terminated, because terminal data legitimately contains NULs (PRD §4.3).
 */
typedef struct TerminalBytes {
    const uint8_t *bytes;
    uint32_t len;
} TerminalBytes;

/**
 * One environment variable for the child process.
 */
typedef struct TerminalEnvPair {
    struct TerminalBytes key;
    struct TerminalBytes value;
} TerminalEnvPair;

/**
 * Everything needed to start a terminal.
 */
typedef struct TerminalConfig {
    struct TerminalSize size;
    /**
     * The program to run, as UTF-8 bytes.
     */
    struct TerminalBytes program;
    /**
     * Its arguments, as an array of byte buffers. May be null when `args_len`
     * is zero.
     */
    const struct TerminalBytes *args;
    uint32_t args_len;
    /**
     * The directory the shell starts in. An empty buffer means the user's home
     * directory, which is what an app bundle wants — its own working directory
     * is `/`.
     */
    struct TerminalBytes cwd;
    /**
     * Extra environment variables, applied over the inherited environment and
     * over the engine's own defaults. May be null when `env_len` is zero.
     *
     * `TERM` and `COLORTERM` are set by the engine whether or not they appear
     * here: what `TERM` names is the engine's capability statement, not the
     * frontend's decoration. Listing them here overrides that.
     */
    const struct TerminalEnvPair *env;
    uint32_t env_len;
    /**
     * The wake-up callback, or null for none. Spelled out rather than written
     * as `Option<TerminalWakeUpFn>`, which cbindgen renders as an opaque
     * struct C cannot fill in — the header is generated precisely so that
     * kind of mismatch is visible instead of silent (PRD §14).
     */
    void (*wake_up)(void *ctx);
    void *wake_up_ctx;
} TerminalConfig;

/**
 * A key press as the view reports it.
 */
typedef struct TerminalKeyEvent {
    TerminalKeyCode code;
    /**
     * The character for [`TerminalKeyCode::Char`], as a Unicode scalar value.
     */
    uint32_t codepoint;
    /**
     * The function-key number, or the keypad digit.
     */
    uint8_t number;
    /**
     * A bit-set of `TERMINAL_MOD_*`.
     */
    uint16_t modifiers;
} TerminalKeyEvent;

/**
 * One run of the visible screen: consecutive columns sharing a style,
 * described as a slice of the frame's text buffer (PRD §10).
 *
 * `fg` and `bg` are packed rather than resolved: `0x00_000000` is the terminal
 * default, `0x01_0000II` a palette index, `0x02_RRGGBB` truecolour. The engine
 * owns no theme, so the frontend resolves them.
 */
typedef struct TerminalRun {
    uint32_t utf8_offset;
    uint32_t utf8_len;
    uint32_t fg;
    uint32_t bg;
    uint16_t row;
    uint16_t col;
    uint16_t cols;
    uint16_t attrs;
} TerminalRun;

/**
 * The caller-owned buffers one frame is copied into. Allocate once, reuse
 * every frame: in the steady state neither side allocates.
 */
typedef struct TerminalFrameBuffers {
    struct TerminalRun *runs;
    uint32_t runs_cap;
    uint8_t *text;
    uint32_t text_cap;
} TerminalFrameBuffers;

/**
 * What was copied, and everything else one redraw needs.
 *
 * Filled in even when the buffers were too small, so the caller learns the
 * sizes it needs and can grow and retry — the two-call sizing pattern of
 * PRD §11, with no allocation to free.
 */
typedef struct TerminalFrameInfo {
    uint32_t runs_len;
    uint32_t text_len;
    uint16_t rows;
    uint16_t cols;
    uint16_t cursor_row;
    uint16_t cursor_col;
    bool cursor_visible;
} TerminalFrameInfo;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Start a shell on a new pty and return the handle.
 *
 * Returns null if the configuration is unusable or the shell cannot start.
 * The caller must pass the handle to [`terminal_destroy`] exactly once.
 *
 * # Safety
 * `config` must point to a valid `TerminalConfig`, whose byte buffers are
 * readable for the duration of the call.
 */
struct TerminalSession *terminal_create(const struct TerminalConfig *config);

/**
 * Stop the terminal and free it. Null is ignored; calling it twice on the same
 * handle is not (PRD §6).
 *
 * This is the ordered shutdown of PRD §7 — the reader thread is signalled and
 * joined, and the shell hung up, before the memory goes away.
 *
 * # Safety
 * `session` must be a handle from [`terminal_create`] that has not yet been
 * destroyed.
 */
void terminal_destroy(struct TerminalSession *session);

/**
 * Send committed text — what the input system produced (PRD §8). The bytes go
 * to the shell unchanged.
 *
 * # Safety
 * `bytes` must point to `len` readable bytes for the duration of the call.
 */
TerminalStatus terminal_send_text(struct TerminalSession *session,
                                  const uint8_t *bytes,
                                  uint32_t len);

/**
 * Send a key press. The engine encodes it against the current modes — DECCKM
 * for the arrows, DECKPAM for the keypad (PRD §8).
 *
 * # Safety
 * `session` must be a live handle from [`terminal_create`].
 */
TerminalStatus terminal_send_key(struct TerminalSession *session, struct TerminalKeyEvent event);

/**
 * Send pasted text, bracketed if the program asked for that (PRD §8).
 *
 * # Safety
 * `bytes` must point to `len` readable bytes for the duration of the call.
 */
TerminalStatus terminal_paste(struct TerminalSession *session, const uint8_t *bytes, uint32_t len);

/**
 * Resize: the engine reflows and the kernel signals the program (PRD §16.4).
 *
 * # Safety
 * `session` must be a live handle from [`terminal_create`].
 */
TerminalStatus terminal_resize(struct TerminalSession *session, uint16_t rows, uint16_t cols);

/**
 * Copy the visible screen into caller-owned buffers (PRD §10-A).
 *
 * One call per frame takes the lock once, so the frame is internally
 * consistent — no tearing between row 3 and row 40. `info` is filled in even
 * when the buffers are too small, so a caller can size its buffers by calling
 * once with zero capacity and again with enough.
 *
 * # Safety
 * `buffers`, when non-null, must describe writable memory of the stated
 * capacities, and `info` must point to a writable `TerminalFrameInfo`.
 */
TerminalStatus terminal_copy_frame(struct TerminalSession *session,
                                   const struct TerminalFrameBuffers *buffers,
                                   struct TerminalFrameInfo *info);

/**
 * Copy the window title (OSC 0/2) as UTF-8 into `buf`.
 *
 * `out_len` always receives the length the title needs, so calling with a zero
 * capacity is how you learn the size (PRD §11). Nothing is copied when the
 * buffer is too small.
 *
 * # Safety
 * `buf`, when non-null, must be writable for `cap` bytes, and `out_len` must
 * point to a writable `u32`.
 */
TerminalStatus terminal_copy_title(struct TerminalSession *session,
                                   uint8_t *buf,
                                   uint32_t cap,
                                   uint32_t *out_len);

/**
 * Whether the shell has exited and the reader thread has stopped.
 *
 * # Safety
 * `out` must point to a writable `bool`.
 */
TerminalStatus terminal_has_hung_up(struct TerminalSession *session, bool *out);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* TERMINAL_H */
